### ISSUE TITLE
Add End of Life text to README

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/phantom-toolbox#14]
## Context

This product is open source and so much comply with our checklist.
Our usual [end-of-life language](https://answers.uillinois.edu/illinois/109544).

## Tasks

- [x] calculate end-of-life for known components: supported Python versions, SOAR API. An educated guess may be required for SOAR API.
- [x] add the end-of-life information to README.md per https://answers.uillinois.edu/illinois/109544

**Comment by mpitcel** [comment]
For Splunk SOAR dates:

https://www.splunk.com/en_us/legal/splunk-software-support-policy.html

**Comment by mpitcel** [comment]
Per this in the setup file, I am using Python v3.9:

https://github.com/techservicesillinois/phantom-toolbox/blob/main/setup.cfg#L29
